### ISSUE TITLE
Error in BreadCrumbs component

### ISSUE THREAD

**Issue by ganeshan** [NetCoreApps/TalentBlazor#1]
When I run the application, I am getting error in the browser console:
`blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object of type 'ServiceStack.Blazor.Components.Tailwind.Breadcrumbs' does not have a property matching the name 'BreadCrumbs'.
System.InvalidOperationException: Object of type 'ServiceStack.Blazor.Components.Tailwind.Breadcrumbs' does not have a property matching the name 'BreadCrumbs'.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, String parameterName)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)`

`BrowserConsoleLogger.js:50  [Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer] Unhandled exception rendering component: Object of type 'ServiceStack.Blazor.Components.Tailwind.Breadcrumbs' does not have a property matching the name 'BreadCrumbs'.`

`BrowserConsoleLogger.js:53  [Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer] Exception: System.InvalidOperationException: Object of type 'ServiceStack.Blazor.Components.Tailwind.Breadcrumbs' does not have a property matching the name 'BreadCrumbs'.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, String parameterName)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
log @ BrowserConsoleLogger.js:53`

**Comment by mythz** [comment]
This issue should now be resolved with the latest version.
